name: test

on: [workflow_call]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: podman
          version: 1.0
      - run: ./scripts/run_gitlab.sh -ci
      - run: ./scripts/wait_for_gitlab.sh
      - run: |
          . ./scripts/request_gitlab_token.sh
          echo "SUSLIK_GITLAB_TOKEN=$SUSLIK_GITLAB_TOKEN" >> $GITHUB_ENV
      - run: go test -tags integration
